USE child_vaccination_db;
ALTER TABLE notification_log
  MODIFY reminder_type ENUM('VACCINE_DUE','VACCINE_OVERDUE','APPOINTMENT','GENERAL') NOT NULL,
  MODIFY related_record_id BIGINT UNSIGNED NULL,
  MODIFY status ENUM('PENDING','PROCESSING','SENT','DELIVERED','FAILED','CANCELLED','SKIPPED') NOT NULL DEFAULT 'PENDING';
